---
title: "Two-Step Kernel Method Exploration: 20 Cell Types with 4 Rare Cell Types - No Effect Sizes were Added (Null Hypothesis)"

# No Effect Sizes were Added (Null Hypothesis)"
# Added to All Cell Types" 
# Added Only to Non-rare Cell Types"
# Only to Rare Cell Types"

author: "Kelvin Njuki"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
#classoption: landscape
---

```{r echo=FALSE, warning=FALSE, include=FALSE}

# Set working directory
setwd("D:/A.School/OSU/Class/1. Dissertation/6. Fall 2024/Simulations/Two-Step Kernel Method")

### Source files
source("D:/A.School/OSU/Class/1. Dissertation/6. Fall 2024/Simulations/Two-Step Kernel Method/CODAK_functions.R")
source("D:/A.School/OSU/Class/1. Dissertation/6. Fall 2024/Simulations/Two-Step Kernel Method/two_step_KDC_v2.R")
source("D:/A.School/OSU/Class/1. Dissertation/6. Fall 2024/Simulations/Two-Step Kernel Method/simulation_functions.R")
source("D:/A.School/OSU/Class/1. Dissertation/6. Fall 2024/Simulations/Two-Step Kernel Method/final_addeffects_fn_version6.R")

# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("SummarizedExperiment")
# BiocManager::install("diffcyt")
# 
# BiocManager::install(version="3.19")
# BiocManager::install( ) # and choose  'a'  for update all to current release.
# BiocManager::valid()

###### Use simulations #######
props.kernel <- c(0.15, 0.13, 0.07, 0.05, 0.1, 0.05, 0.05,
           0.05, 0.02, 0.1, 0.02, 0.003, 0.002, 0.004,
           0.12, 0.04, 0.004, 0.007, 0.02, 0.01)

# Comments on this part if generating data for 10 small ps
# #Proportions for generating data with zeros
props.pseudo <- props.kernel

props.pseudo[4] <- 9e-5
props.pseudo[6] <- props.pseudo[6] + 0.05 - 9e-5
props.pseudo[9] <- 7e-5
props.pseudo[11] <- props.pseudo[11] + 0.02 - 7e-5
props.pseudo[12] <- 5e-5
props.pseudo[15] <- props.pseudo[15] + 0.003 - 5e-5
props.pseudo[17] <- 6e-5
props.pseudo[18] <- props.pseudo[18] + 0.004 - 6e-5


# # Comments on this part if generating data for 3 small ps
# #Proportions for generating data with zeros
# props.pseudo <- props.kernel
# 
# i <- 1
# while (i <= 20){
#   props.pseudo[i] <- props.kernel[i]*1e-3
#   props.pseudo[i+1] <- props.kernel[i+1] + props.kernel[i] - props.pseudo[i]
#   i <- i + 2
# }

num.cat <- length(props.pseudo)
num.perm <- 10000

#12 observations in each group 
ng <- 12
Xmat <- matrix(rep(c(0, 1), each = ng), ncol = 1)

#number of events for the individual samples
set.seed(92486)
nvec <- sample(c(30000, 40000, 50000), 2*ng, replace = T)

#covariance matrix of random effects
set.seed(92486)
sigbvec <- rep(0.2, num.cat-1) 
sigb <- diag(num.cat-1)*sigbvec^2


set.seed(123)

#num.sim <- 1

betarev1 <- getES.mlogit(props.pseudo)

############ 4 smallp's
props.pseudo.new <- props.pseudo # none changed (null hypothesis)
# props.pseudo.new <- add.new.effects(maxeffect = 0.004, prop=props.pseudo,  n.nochange = 0,
#                                     ind.nochange = NULL) # all cell types changed
# props.pseudo.new <- add.new.effects(maxeffect = 0.04, prop=props.pseudo,  n.nochange = 0,
#                                     ind.nochange = c(4,9,12,17)) # only nonrare cell types changed
# props.pseudo.new <- add.new.effects(maxeffect = 6.5e-05, prop=props.pseudo,  n.nochange = 0,
#                                     ind.nochange = seq(1,20)[-c(4,9,12,17)]) # only rare cell types changed


############ 10 smallp's
# props.pseudo.new <- props.pseudo # none changed (null hypothesis)
# props.pseudo.new <- add.new.effects(maxeffect = 0.004, prop=props.pseudo,  n.nochange = 0,
#                                     ind.nochange = NULL) # all cell types changed
# props.pseudo.new <- add.new.effects(maxeffect = 0.004, prop=props.pseudo,  n.nochange = 0,
#                                     ind.nochange = seq(1,20,2)) # only nonrare cell types changed
# props.pseudo.new <- add.new.effects(maxeffect = 0.004, prop=props.pseudo,  n.nochange = 0,
#                                     ind.nochange = seq(2,20,2)) # only rare cell types changed

betarev2 <- getES.mlogit(props.pseudo.new)
betaX <- as.matrix(betarev2 - betarev1)

#x is the predictor of interest. Works for only one predictor.
x <- as.vector(Xmat)
xvec <- as.vector(Xmat)
  
y <- simProps(beta=betarev1, betaX, Xmat, nvec, sigb)

#ng <- nrow(y)/2
#num.cat <- ncol(y)
propmat <- y/rep(nvec, num.cat)


# Replacing the zeros with 1
propmat.0.impute <- matrix(NA, nrow = nrow(y), ncol = ncol(y))
  
  for (i in 1:length(y)){
    if (y[i] == 0) {propmat.0.impute[i] <- 1} else {propmat.0.impute[i] <- y[i]} 
  }

# Taking closure after replacing zeros
propmat1 <- propmat.0.impute/rowSums(propmat.0.impute)
```

<!-- ### Step One: Hamming Distance; Step Two: Aitchison, BCD, Canberra & Euclidean; Step Two Subcompositions not normalized; Kernels combined through sum. -->

```{r echo=FALSE, fig.cap="In the first row, zeros are replaced by 1. In the second row, we are implementing two step kernel where in step one, Hamming Distance was used; in step two Aitchison, BCD, Canberra & Euclidean were used; Closure was not applied in step two; Kernels (K1 & K2) were combined through Sum."}

# Set up a layout: 3 plot columns + 1 legend row
layout(matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol=4, byrow = TRUE), heights = c(1, 1, 1))

# Adjust plot margins to reduce whitespace
par(mar = c(4, 4, 2, 1))

distvec0 <- c("Aitchison Zeros-Imputed", "Canberra Zeros-Imputed", "Canberra No Zeros-Imputed")

for (i in 1:3){
  if (i == 1){
    d <- dist(propmat1, method = 'aitchison') # zeros imputed
  }
  if (i == 2){
    d <- vegdist(propmat1, method="canberra") # zeros imputed
  }
  if (i == 3){
    d <- vegdist(propmat, method = 'canberra') # no zeros imputed
  }
  
  alldist <- as.numeric(d)
  K <- as.matrix(exp(-d/median(alldist)))
  
  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  xx <- xx[-which(xx == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)), 
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec0[i], font.main = 1, cex.main = 1)
  
  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}
####################################################################################################

distvec2 <- c("Canberra Two-Step", "Aitchison Two-Step", "Bray-Curtis Two-Step", "Euclidean Two-Step")
distvec <- c("Canberra", "Aitchison", "Bray-Curtis", "Euclidean")

for (i in 1:4){
  
  if (i == 1){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "hamming", compdist2 = "canberra", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
    }
  
  if (i == 2){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "hamming", compdist2 = "aitchison", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 3){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "hamming", compdist2 = "BCD", combinethru="sum", gaussian = F, 
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 4){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "hamming", compdist2 = "euclidean", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }


  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)), 
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec2[i], font.main = 1, cex.main = 1)

  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}

# Plot an empty frame for the side legend
plot.new()

# Side legend
legend("top", inset = 0,
       legend = c("Step 1: Hamming", paste("Step 2:", distvec),
                  "Closure: No", "Combine: Sum", "Effect Size = None"),
       bty = "n", cex = 0.8, text.font = 1)

```



<!-- ### Step One: Hamming Distance; Step Two: Aitchison, BCD & Euclidean; Step Two Subcompositions normalized; Kernels combined through sum. -->

```{r echo=FALSE, fig.cap="In the first row, zeros are replaced by 1. In the second row, we are implementing two step kernel where in step one, Hamming Distance was used; in step two Aitchison, BCD, Canberra & Euclidean were used; Closure was applied in step two; Kernels (K1 & K2) were combined through Sum."}

# Set up a layout: 3 plot columns + 1 legend row
layout(matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol=4, byrow = TRUE), heights = c(1, 1, 1))

# Adjust plot margins to reduce whitespace
par(mar = c(4, 4, 2, 1))

distvec0 <- c("Aitchison Zeros-Imputed", "Canberra Zeros-Imputed", "Canberra No Zeros-Imputed")


for (i in 1:3){
  if (i == 1){
    d <- dist(propmat1, method = 'aitchison')
  }
  if (i == 2){
    d <- vegdist(propmat1, method="canberra")
  }
  if (i == 3){
    d <- vegdist(propmat, method = 'canberra')
  }
  
  alldist <- as.numeric(d)
  K <- as.matrix(exp(-d/median(alldist)))
  
  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  xx <- xx[-which(xx == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)), 
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec0[i], font.main = 1, cex.main = 1)
  
  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}
####################################################################################################

distvec2 <- c("Canberra Two-Step", "Aitchison Two-Step", "Bray-Curtis Two-Step", "Euclidean Two-Step")
distvec <- c("Canberra", "Aitchison", "Bray-Curtis", "Euclidean")

for (i in 1:4){
  if (i == 1){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "hamming", compdist2 = "canberra", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  if (i == 2){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "hamming", compdist2 = "aitchison", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 3){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "hamming", compdist2 = "BCD", combinethru="sum", gaussian = F, 
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 4){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "hamming", compdist2 = "euclidean", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }


  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  #xx <- xx[-which(xx == 2)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec2[i], font.main = 1, cex.main = 1)

  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}

# Plot an empty frame for the side legend
plot.new()

# Side legend
legend("top", inset = 0,
       legend = c("Step 1: Hamming", paste("Step 2:", distvec),
                  "Closure: Yes", "Combine: Sum", "Effect Size = None"),
       bty = "n", cex = 0.8, text.font = 1)
```


<!-- ### Step One: Jaccard Distance; Step Two: Aitchison, BCD & Euclidean; Step Two Subcompositions not normalized; Kernels combined through sum. -->

```{r echo=FALSE, fig.cap="In the first row, zeros are replaced by 1. In the second row, we are implementing two step kernel where in step one, Jaccard Distance was used; in step two Aitchison, BCD, Canberra & Euclidean were used; Closure was not applied in step two; Kernels (K1 & K2) were combined through Sum."}

# Set up a layout: 3 plot columns + 1 legend row
layout(matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol=4, byrow = TRUE), heights = c(1, 1, 1))

# Adjust plot margins to reduce whitespace
par(mar = c(4, 4, 2, 1))

distvec0 <- c("Aitchison Zeros-Imputed", "Canberra Zeros-Imputed", "Canberra No Zeros-Imputed")


for (i in 1:3){
  if (i == 1){
    d <- dist(propmat1, method = 'aitchison')
  }
  if (i == 2){
    d <- vegdist(propmat1, method="canberra")
  }
  if (i == 3){
    d <- vegdist(propmat, method = 'canberra')
  }
  
  alldist <- as.numeric(d)
  K <- as.matrix(exp(-d/median(alldist)))
  
  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  xx <- xx[-which(xx == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)), 
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)),
       main = distvec0[i], font.main = 1, cex.main = 1)
  
  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}
####################################################################################################

distvec2 <- c("Canberra Two-Step", "Aitchison Two-Step", "Bray-Curtis Two-Step", "Euclidean Two-Step")
distvec <- c("Canberra", "Aitchison", "Bray-Curtis", "Euclidean")

for (i in 1:4){
  if (i == 1){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "jaccard", compdist2 = "canberra", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  if (i == 2){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "jaccard", compdist2 = "aitchison", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 3){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "jaccard", compdist2 = "BCD", combinethru="sum", gaussian = F, 
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 4){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "jaccard", compdist2 = "euclidean", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }


  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  #xx <- xx[-which(xx == 2)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec2[i], font.main = 1, cex.main = 1)

  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}

# Plot an empty frame for the side legend
plot.new()

# Side legend
legend("top", inset = 0,
       legend = c("Step 1: Jaccard", paste("Step 2:", distvec),
                  "Closure: No", "Combine: Sum", "Effect Size = None"),
       bty = "n", cex = 0.8, text.font = 1)
```


<!-- ### Step One: Jaccard Distance; Step Two: Aitchison, BCD & Euclidean; Step Two Subcompositions normalized; Kernels combined through sum. -->

```{r echo=FALSE, fig.cap="In the first row, zeros are replaced by 1. In the second row, we are implementing two step kernel where in step one, Jaccard Distance was used; in step two Aitchison, BCD, Canberra & Euclidean were used; Closure was applied in step two; Kernels (K1 & K2) were combined through Sum."}

# Set up a layout: 3 plot columns + 1 legend row
layout(matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol=4, byrow = TRUE), heights = c(1, 1, 1))

# Adjust plot margins to reduce whitespace
par(mar = c(4, 4, 2, 1))

distvec0 <- c("Aitchison Zeros-Imputed", "Canberra Zeros-Imputed", "Canberra No Zeros-Imputed")


for (i in 1:3){
  if (i == 1){
    d <- dist(propmat1, method = 'aitchison')
  }
  if (i == 2){
    d <- vegdist(propmat1, method="canberra")
  }
  if (i == 3){
    d <- vegdist(propmat, method = 'canberra')
  }
  
  alldist <- as.numeric(d)
  K <- as.matrix(exp(-d/median(alldist)))
  
  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  xx <- xx[-which(xx == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec0[i], font.main = 1, cex.main = 1)
  
  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}
####################################################################################################

distvec2 <- c("Canberra Two-Step", "Aitchison Two-Step", "Bray-Curtis Two-Step", "Euclidean Two-Step")
distvec <- c("Canberra", "Aitchison", "Bray-Curtis", "Euclidean")

for (i in 1:4){
  if (i == 1){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "jaccard", compdist2 = "canberra", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  if (i == 2){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "jaccard", compdist2 = "aitchison", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 3){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "jaccard", compdist2 = "BCD", combinethru="sum", gaussian = F, 
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 4){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "jaccard", compdist2 = "euclidean", combinethru="sum", gaussian = F,
                           result = "test")
    K <- out$K
    
  }


  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  #xx <- xx[-which(xx == 2)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec2[i], font.main = 1, cex.main = 1)

  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}

# Plot an empty frame for the side legend
plot.new()

# Side legend
legend("top", inset = 0,
       legend = c("Step 1: Jaccard", paste("Step 2:", distvec),
                  "Closure: Yes", "Combine: Sum", "Effect Size = None"),
       bty = "n", cex = 0.8, text.font = 1)
```



<!-- ### Step One: Hamming Distance; Step Two: Aitchison, BCD & Euclidean; Step Two Subcompositions not normalized; Kernels combined through product. -->

```{r echo=FALSE, fig.cap="In the first row, zeros are replaced by 1. In the second row, we are implementing two step kernel where in step one, Hamming Distance was used; in step two Aitchison, BCD, Canberra & Euclidean were used; Closure was not applied in step two; Kernels (K1 & K2) were combined through Product."}

# Set up a layout: 3 plot columns + 1 legend row
layout(matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol=4, byrow = TRUE), heights = c(1, 1, 1))

# Adjust plot margins to reduce whitespace
par(mar = c(4, 4, 2, 1))

distvec0 <- c("Aitchison Zeros-Imputed", "Canberra Zeros-Imputed", "Canberra No Zeros-Imputed")


for (i in 1:3){
  if (i == 1){
    d <- dist(propmat1, method = 'aitchison')
  }
  if (i == 2){
    d <- vegdist(propmat1, method="canberra")
  }
  if (i == 3){
    d <- vegdist(propmat, method = 'canberra')
  }
  
  alldist <- as.numeric(d)
  K <- as.matrix(exp(-d/median(alldist)))
  
  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  xx <- xx[-which(xx == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)), 
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec0[i], font.main = 1, cex.main = 1)
  
  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}
####################################################################################################

distvec2 <- c("Canberra Two-Step", "Aitchison Two-Step", "Bray-Curtis Two-Step", "Euclidean Two-Step")
distvec <- c("Canberra", "Aitchison", "Bray-Curtis", "Euclidean")

for (i in 1:4){
  if (i == 1){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "hamming", compdist2 = "canberra", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  if (i == 2){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "hamming", compdist2 = "aitchison", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 3){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "hamming", compdist2 = "BCD", combinethru="product", gaussian = F, 
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 4){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "hamming", compdist2 = "euclidean", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }


  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  #xx <- xx[-which(xx == 2)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec2[i], font.main = 1, cex.main = 1)

  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}


# Plot an empty frame for the side legend
plot.new()

# Side legend
legend("top", inset = 0,
       legend = c("Step 1: Hamming", paste("Step 2:", distvec),
                  "Closure: No", "Combine: Sum", "Effect Size = None"),
       bty = "n", cex = 0.8, text.font = 1)
```



<!-- ### Step One: Hamming Distance; Step Two: Aitchison, BCD & Euclidean; Step Two Subcompositions normalized; Kernels combined through product. -->

```{r echo=FALSE, fig.cap="In the first row, zeros are replaced by 1. In the second row, we are implementing two step kernel where in step one, Hamming Distance was used; in step two Aitchison, BCD, Canberra & Euclidean were used; Closure was applied in step two; Kernels (K1 & K2) were combined through Product"}

# Set up a layout: 3 plot columns + 1 legend row
layout(matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol=4, byrow = TRUE), heights = c(1, 1, 1))

# Adjust plot margins to reduce whitespace
par(mar = c(4, 4, 2, 1))

distvec0 <- c("Aitchison Zeros-Imputed", "Canberra Zeros-Imputed", "Canberra No Zeros-Imputed")


for (i in 1:3){
  if (i == 1){
    d <- dist(propmat1, method = 'aitchison')
  }
  if (i == 2){
    d <- vegdist(propmat1, method="canberra")
  }
  if (i == 3){
    d <- vegdist(propmat, method = 'canberra')
  }
  
  alldist <- as.numeric(d)
  K <- as.matrix(exp(-d/median(alldist)))
  
  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  xx <- xx[-which(xx == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec0[i], font.main = 1, cex.main = 1)
  
  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}
####################################################################################################

distvec2 <- c("Canberra Two-Step", "Aitchison Two-Step", "Bray-Curtis Two-Step", "Euclidean Two-Step")
distvec <- c("Canberra", "Aitchison", "Bray-Curtis", "Euclidean")

for (i in 1:4){
  if (i == 1){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "hamming", compdist2 = "canberra", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  if (i == 2){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "hamming", compdist2 = "aitchison", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 3){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "hamming", compdist2 = "BCD", combinethru="product", gaussian = F, 
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 4){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "hamming", compdist2 = "euclidean", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }


  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  #xx <- xx[-which(xx == 2)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec2[i], font.main = 1, cex.main = 1)

  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}


# Plot an empty frame for the side legend
plot.new()

# Side legend
legend("top", inset = 0,
       legend = c("Step 1: Hamming", paste("Step 2:", distvec),
                  "Closure: Yes", "Combine: Sum", "Effect Size = None"),
       bty = "n", cex = 0.8, text.font = 1)
```



<!-- ### Step One: Jaccard Distance; Step Two: Aitchison, BCD & Euclidean; Step Two Subcompositions not normalized; Kernels combined through product. -->

```{r echo=FALSE, fig.cap="In the first row, zeros are replaced by 1. In the second row, we are implementing two step kernel where in step one, Jaccard Distance was used; in step two Aitchison, BCD, Canberra & Euclidean were used; Closure was not applied in step two; Kernels (K1 & K2) were combined through Product"}

# Set up a layout: 3 plot columns + 1 legend row
layout(matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol=4, byrow = TRUE), heights = c(1, 1, 1))

# Adjust plot margins to reduce whitespace
par(mar = c(4, 4, 2, 1))

distvec0 <- c("Aitchison Zeros-Imputed", "Canberra Zeros-Imputed", "Canberra No Zeros-Imputed")


for (i in 1:3){
  if (i == 1){
    d <- dist(propmat1, method = 'aitchison')
  }
  if (i == 2){
    d <- vegdist(propmat1, method="canberra")
  }
  if (i == 3){
    d <- vegdist(propmat, method = 'canberra')
  }
  
  alldist <- as.numeric(d)
  K <- as.matrix(exp(-d/median(alldist)))
  
  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  xx <- xx[-which(xx == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec0[i], font.main = 1, cex.main = 1)
  
  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}
####################################################################################################

distvec2 <- c("Canberra Two-Step", "Aitchison Two-Step", "Bray-Curtis Two-Step", "Euclidean Two-Step")
distvec <- c("Canberra", "Aitchison", "Bray-Curtis", "Euclidean")

for (i in 1:4){
  if (i == 1){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "jaccard", compdist2 = "canberra", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  if (i == 2){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "jaccard", compdist2 = "aitchison", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 3){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "jaccard", compdist2 = "BCD", combinethru="product", gaussian = F, 
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 4){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "No",
                           compdist1 = "jaccard", compdist2 = "euclidean", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }


  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  #xx <- xx[-which(xx == 2)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec2[i], font.main = 1, cex.main = 1)

  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}

# Plot an empty frame for the side legend
plot.new()

# Side legend
legend("top", inset = 0,
       legend = c("Step 1: Jaccard", paste("Step 2:", distvec),
                  "Closure: No", "Combine: Sum", "Effect Size = None"),
       bty = "n", cex = 0.8, text.font = 1)
```


<!-- ### Step One: Jaccard Distance; Step Two: Aitchison, BCD & Euclidean; Step Two Subcompositions normalized; Kernels combined through product. -->

```{r echo=FALSE, fig.cap="In the first row, zeros are replaced by 1. In the second row, we are implementing two step kernel where in step one, Jaccard Distance was used; in step two Aitchison, BCD, Canberra & Euclidean were used; Closure was applied in step two; Kernels (K1 & K2) were combined through Product"}

# Set up a layout: 3 plot columns + 1 legend row
layout(matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol=4, byrow = TRUE), heights = c(1, 1, 1))

# Adjust plot margins to reduce whitespace
par(mar = c(4, 4, 2, 1))

distvec0 <- c("Aitchison Zeros-Imputed", "Canberra Zeros-Imputed", "Canberra No Zeros-Imputed")


for (i in 1:3){
  if (i == 1){
    d <- dist(propmat1, method = 'aitchison')
  }
  if (i == 2){
    d <- vegdist(propmat1, method="canberra")
  }
  if (i == 3){
    d <- vegdist(propmat, method = 'canberra')
  }
  
  alldist <- as.numeric(d)
  K <- as.matrix(exp(-d/median(alldist)))
  
  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  xx <- xx[-which(xx == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec0[i], font.main = 1, cex.main = 1)
  
  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}
####################################################################################################

distvec2 <- c("Canberra Two-Step", "Aitchison Two-Step", "Bray-Curtis Two-Step", "Euclidean Two-Step")
distvec <- c("Canberra", "Aitchison", "Bray-Curtis", "Euclidean")

for (i in 1:4){
  if (i == 1){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "jaccard", compdist2 = "canberra", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  if (i == 2){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "jaccard", compdist2 = "aitchison", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 3){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "jaccard", compdist2 = "BCD", combinethru="product", gaussian = F, 
                           result = "test")
    K <- out$K
    
  }
  
  
  if (i == 4){
    
    out <- dcor.comp.2step(propmat, xvec, num.perm = 1e4, Xdist = "categorical", closure = "Yes",
                           compdist1 = "jaccard", compdist2 = "euclidean", combinethru="product", gaussian = F,
                           result = "test")
    K <- out$K
    
  }


  xx <- c(K[which(x == 1), which(x == 1)], K[which(x == 0), which(x == 0)])
  
  yy <- K[which(x == 1), which(x == 0)]
  
  plot(density(xx), col = "red", xlab = "Similarity", 
       xlim = c(min(density(xx)$x, density(yy)$x), max(density(xx)$x, density(yy)$x)),
       ylim = c(min(density(xx)$y, density(yy)$y), max(density(xx)$y, density(yy)$y)), 
       main = distvec2[i], font.main = 1, cex.main = 1)

  lines(density(yy), col = "blue")
  
  legend("topright", legend = c("Same group", "Different group"), col = c("red", "blue"), 
         lty = c(1, 1), cex = 0.7)
}

# Plot an empty frame for the side legend
plot.new()

# Side legend
legend("top", inset = 0,
       legend = c("Step 1: Jaccard", paste("Step 2:", distvec),
                  "Closure: Yes", "Combine: Sum", "Effect Size = None"),
       bty = "n", cex = 0.8, text.font = 1)
```


